#!/usr/sbin/nft -f

flush ruleset

define RESERVED_IP = {
    10.0.0.0/8,
    100.64.0.0/10,
    127.0.0.0/8,
    169.254.0.0/16,
    172.16.0.0/12,
    192.0.0.0/24,
    224.0.0.0/4,
    240.0.0.0/4,
    255.255.255.255/32
}

table ip xray {
    chain prerouting {
        # use raw priority so this sees packets before Docker's NAT
        type filter hook prerouting priority raw; policy accept;

        # Catch traffic coming from containers (docker0). Jump to proxy_mark
        iifname "docker0" ip daddr != 127.0.0.1 jump proxy_mark

        # Host & LAN traffic (existing rules)
        ip daddr $RESERVED_IP return
        tcp dport 22 return
        udp dport 22 return
        tcp dport 8585 return
        udp dport 8585 return
        ip daddr 192.168.0.0/16 tcp dport != 53 return
        ip daddr 192.168.0.0/16 udp dport != 53 return
        ip protocol tcp tproxy to 127.0.0.1:12345 meta mark set 1
        ip protocol udp tproxy to 127.0.0.1:12345 meta mark set 1
    }

    chain output {
        type route hook output priority mangle; policy accept;
        ip daddr $RESERVED_IP return
        tcp sport 22 return
        udp sport 22 return
        tcp sport 8585 return
        udp sport 8585 return
        ip daddr 192.168.0.0/16 tcp dport != 53 return
        ip daddr 192.168.0.0/16 udp dport != 53 return
        meta mark 2 return
        ip protocol tcp meta mark set 1
        ip protocol udp meta mark set 1
    }

    chain proxy_mark {
        ip daddr $RESERVED_IP return
        tcp dport 22 return
        udp dport 22 return
        tcp dport 8585 return
        udp dport 8585 return
        ip daddr 192.168.0.0/16 tcp dport != 53 return
        ip daddr 192.168.0.0/16 udp dport != 53 return

        # mark and redirect to local transparent proxy
        ip protocol tcp tproxy to 127.0.0.1:12345 meta mark set 1
        ip protocol udp tproxy to 127.0.0.1:12345 meta mark set 1
    }
}
